import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Navbar } from "./_components/navbar";
import { Suspense } from "react";
import * as Controller from './_components/controller'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="titlebar" />
        <Controller.Provider>
          <Suspense>
              <Navbar />
              { children }
          </Suspense>
        </Controller.Provider>
      </body>
    </html>
  )
}